/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef FITF
#define FITF

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class fitf : public RooAbsPdf {
public:
  fitf() {} ; 
  fitf(const char *name, const char *title,
	      RooAbsReal& _t,
          RooAbsCategory& _n,
	      RooAbsReal& _N0,
       RooAbsReal& _lamA,
       RooAbsReal& _lamB,
       RooAbsReal& _lamC,
       RooAbsReal& _lamD,
       RooAbsReal& _lamE,
       RooAbsReal& _lamF,
       RooAbsReal& _lamG,
       RooAbsReal& _lamH,
       RooAbsReal& _lamI,
       RooAbsReal& _lamJ,
       RooAbsReal& _lamK,
       RooAbsReal& _lamL,
       RooAbsReal& _p1A,
       RooAbsReal& _p1B,
       RooAbsReal& _p1C,
       RooAbsReal& _p1D,
       RooAbsReal& _p1E,
       RooAbsReal& _p1F,
       RooAbsReal& _p1G,
       RooAbsReal& _p1H,
       RooAbsReal& _p1I,
       RooAbsReal& _p1J,
       RooAbsReal& _p1K,
       RooAbsReal& _p2A,
       RooAbsReal& _p2B,
       RooAbsReal& _p2C,
       RooAbsReal& _p2D,
       RooAbsReal& _p2E,
       RooAbsReal& _p2F,
       RooAbsReal& _p2G,
       RooAbsReal& _p2H,
       RooAbsReal& _p2I,
       RooAbsReal& _p2J,
       RooAbsReal& _p2K,
       RooAbsReal& _neuEff,
       RooAbsReal& _bkg1,
       RooAbsReal& _bkg2,
       RooAbsReal& _bkg3,
       RooAbsReal& _rc1,
       RooAbsReal& _rc2,
       RooAbsReal& _neudEff);
  fitf(const fitf& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new fitf(*this,newname); }
  inline virtual ~fitf() { }

protected:

  RooRealProxy t ;
    RooCategoryProxy n ;
  RooRealProxy N0 ;
    RooRealProxy lamA ;
    RooRealProxy lamB ;
    RooRealProxy lamC ;
    RooRealProxy lamD ;
    RooRealProxy lamE ;
    RooRealProxy lamF ;
    RooRealProxy lamG ;
    RooRealProxy lamH ;
    RooRealProxy lamI ;
    RooRealProxy lamJ ;
    RooRealProxy lamK ;
    RooRealProxy lamL ;
    RooRealProxy p1A ;
    RooRealProxy p1B ;
    RooRealProxy p1C ;
    RooRealProxy p1D ;
    RooRealProxy p1E ;
    RooRealProxy p1F ;
    RooRealProxy p1G ;
    RooRealProxy p1H ;
    RooRealProxy p1I ;
    RooRealProxy p1J ;
    RooRealProxy p1K ;
    RooRealProxy p2A ;
    RooRealProxy p2B ;
    RooRealProxy p2C ;
    RooRealProxy p2D ;
    RooRealProxy p2E ;
    RooRealProxy p2F ;
    RooRealProxy p2G ;
    RooRealProxy p2H ;
    RooRealProxy p2I ;
    RooRealProxy p2J ;
    RooRealProxy p2K;
    RooRealProxy neuEff;
    RooRealProxy bkg1 ;
    RooRealProxy bkg2 ;
    RooRealProxy bkg3 ;
    RooRealProxy rc1;
    RooRealProxy rc2;
    RooRealProxy neudEff;
    
    //CALL OTHER DEFINED FUNCTION HERE
    Double_t funcA(double *x, double *p)const;
    Double_t funcB(double *x, double *p)const;
    Double_t funcC(double *x, double *p)const;
    Double_t funcD(double *x, double *p)const;
    Double_t funcE(double *x, double *p)const;
    Double_t funcF(double *x, double *p)const;
    Double_t funcG(double *x, double *p)const;
    Double_t funcH(double *x, double *p)const;
    Double_t funcI(double *x, double *p)const;
    Double_t funcJ(double *x, double *p)const;
    Double_t funcK(double *x, double *p)const;
    Double_t funcL(double *x, double *p)const;
    Double_t FT(double *x, double *p)const;
    Double_t F1NT(double *x, double *p)const;
    Double_t F2NT(double *x, double *p)const;
    Double_t F0NT(double *x, double *p)const;
    Double_t evaluate() const ;

private:

  ClassDef(fitf,1) // Your description goes here...
};
 
#endif
